[[redirects]]
  from = "/main/gateway/sw.js"
  to = "/main/gateway/sw.js"
  status = 200

[[redirects]]
  from = "/main/gateway/manifest.json"
  to = "/main/gateway/manifest.json"
  status = 200

[[redirects]]
  from = "/main/gateway/*"
  to = "/main/gateway/server.html"
  status = 200

[[headers]]
  for = "/main/gateway/sw.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/main/gateway/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
